from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List


class ArtifactsCenterService:
    """Operator-facing artifact guidance.

    GitHub artifact URLs are generated by Actions and may require login. This
    service gives the Home a stable, mobile-friendly map of canonical build
    workflows, expected artifact names, and install next steps.
    """

    REPO_URL = "https://github.com/AndreVazao/devops-god-mode"

    def build_dashboard(self) -> Dict[str, Any]:
        artifacts = self._artifact_targets()
        workflow_checks = self._workflow_checks()
        ready_count = sum(1 for item in workflow_checks if item["present"])
        missing = [item for item in workflow_checks if not item["present"]]
        missing_required = [item for item in missing if item.get("required", False)]
        return {
            "ok": True,
            "mode": "artifacts_center_dashboard",
            "status": "ready" if not missing_required else "missing_required_workflows",
            "repo_url": self.REPO_URL,
            "actions_url": f"{self.REPO_URL}/actions",
            "latest_artifacts_url": f"{self.REPO_URL}/actions?query=branch%3Amain",
            "artifact_count": len(artifacts),
            "ready_workflow_count": ready_count,
            "missing_workflows": missing,
            "missing_required_workflows": missing_required,
            "artifacts": artifacts,
            "install_order": [
                {"step": 1, "label": "Abrir GitHub Actions", "url": f"{self.REPO_URL}/actions"},
                {"step": 2, "label": "Abrir último run verde em main", "url": f"{self.REPO_URL}/actions?query=branch%3Amain"},
                {"step": 3, "label": "Obter GodModeMobile-debug.apk", "artifact": "godmode-android-webview-apk"},
                {"step": 4, "label": "Obter EXE Windows", "artifact": "godmode-windows-exe"},
                {"step": 5, "label": "Abrir EXE no PC e depois APK no telemóvel", "route": "/app/home"},
            ],
            "operator_note": "Os links diretos finais dependem do run do GitHub Actions. A Home mostra o caminho canónico e nomes dos artifacts.",
        }

    def _workflow_checks(self) -> List[Dict[str, Any]]:
        return [
            {
                "id": "apk_build",
                "label": "Android APK Build",
                "path": ".github/workflows/android-real-build-progressive.yml",
                "required": True,
                "present": Path(".github/workflows/android-real-build-progressive.yml").exists(),
            },
            {
                "id": "windows_exe_build",
                "label": "Windows EXE Build",
                "path": ".github/workflows/windows-exe-build.yml",
                "required": True,
                "present": Path(".github/workflows/windows-exe-build.yml").exists(),
            },
            {
                "id": "universal_total_test",
                "label": "Universal Total Test",
                "path": ".github/workflows/universal-total-test.yml",
                "required": False,
                "present": Path(".github/workflows/universal-total-test.yml").exists(),
            },
        ]

    def _artifact_targets(self) -> List[Dict[str, Any]]:
        return [
            {
                "id": "apk",
                "label": "God Mode Android APK",
                "expected_artifact_name": "godmode-android-webview-apk",
                "expected_file": "GodModeMobile-debug.apk",
                "workflow": "Android APK Build",
                "workflow_path": ".github/workflows/android-real-build-progressive.yml",
                "install_target": "Telemóvel Android",
                "next_step": "Instalar APK e abrir; deve entrar em /app/home.",
            },
            {
                "id": "exe",
                "label": "God Mode Windows EXE",
                "expected_artifact_name": "godmode-windows-exe",
                "expected_file": "GodMode.exe",
                "workflow": "Windows EXE Build",
                "workflow_path": ".github/workflows/windows-exe-build.yml",
                "install_target": "PC Windows",
                "next_step": "Abrir no PC para servir o backend local.",
            },
        ]

    def get_status(self) -> Dict[str, Any]:
        dashboard = self.build_dashboard()
        return {
            "ok": True,
            "mode": "artifacts_center_status",
            "status": dashboard["status"],
            "artifact_count": dashboard["artifact_count"],
            "ready_workflow_count": dashboard["ready_workflow_count"],
            "actions_url": dashboard["actions_url"],
        }

    def get_package(self) -> Dict[str, Any]:
        return {"ok": True, "mode": "artifacts_center_package", "package": {"status": self.get_status(), "dashboard": self.build_dashboard()}}


artifacts_center_service = ArtifactsCenterService()
