from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["conversation-source-import-feed-frontend"])

HTML = """
<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Conversation Import</title><style>:root{color-scheme:dark;--panel:#0f172a;--line:#26344f;--text:#eef5ff;--muted:#9fb0d0}*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:radial-gradient(circle at top,#123256,#050816 55%);color:var(--text)}.page{padding:10px;display:grid;gap:10px}.panel{background:rgba(15,23,42,.94);border:1px solid var(--line);border-radius:22px;padding:13px}h1,h2{margin:.1rem 0}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:8px}.buttons{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}button,input,textarea{font:inherit;border-radius:16px;border:1px solid var(--line);background:#0b1220;color:var(--text);padding:12px}button{background:linear-gradient(135deg,#0284c7,#38bdf8);border:none;color:#02101b;font-weight:1000}button.dark{background:#0b1220;color:var(--text);border:1px solid var(--line)}textarea{width:100%;min-height:260px}pre{white-space:pre-wrap;overflow:auto;font-size:12px;max-height:520px;background:#081226;border:1px solid var(--line);border-radius:18px;padding:12px}@media(max-width:760px){.buttons{grid-template-columns:1fr}}</style></head><body><div class="page"><section class="panel"><h1>Conversation Source Import</h1><p class="muted">Cola conversas/transcrições. O God Mode separa Oner vs IA, alimenta o Ledger e liga ao Real Work Map.</p><div class="buttons"><button onclick="location.href='/app/home'" class="dark">Home</button><button onclick="location.href='/app/real-work-fast-path'" class="dark">Trabalho Real</button><button onclick="dashboard()">Dashboard</button></div></section><section class="panel"><h2>Dados</h2><div class="grid"><input id="title" value="Conversa importada"/><input id="provider" value="chatgpt"/><input id="project" value="GOD_MODE"/></div><p class="muted">Usa labels: Oner:, User:, Assistant:, ChatGPT:, Claude:, Gemini:. Sem labels cria card de revisão.</p><textarea id="text">Oner: Preciso que o God Mode liste conversas e repos, separe os meus pedidos das respostas das IAs e ligue ao mapa real do projeto.
Assistant: Proposta: criar importador de conversas, alimentar ledger e Real Work Map. Validar com smoke e builds.</textarea><div class="buttons"><button onclick="importText()">Importar conversa</button><button class="dark" onclick="cards()">Criar cards revisão</button></div></section><section class="panel"><h2>Resultado</h2><pre id="out"></pre></section></div><script>const qs=s=>document.querySelector(s);async function api(p,o){const r=await fetch(p,o);const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={raw:t}};if(!r.ok)throw new Error(t);return j}function show(x){qs('#out').textContent=JSON.stringify(x,null,2)}async function importText(){show(await api('/api/conversation-source-import-feed/import-text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:qs('#title').value,provider:qs('#provider').value,project_hint:qs('#project').value,transcript_text:qs('#text').value})}))}async function cards(){show(await api('/api/conversation-source-import-feed/create-review-cards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})}))}async function dashboard(){show(await api('/api/conversation-source-import-feed/dashboard'))}dashboard()</script></body></html>
"""


@router.get('/app/conversation-source-import-feed', response_class=HTMLResponse)
async def conversation_source_import_feed_frontend() -> HTMLResponse:
    return HTMLResponse(content=HTML)


@router.get('/app/conversation-import', response_class=HTMLResponse)
async def conversation_import_alias() -> HTMLResponse:
    return HTMLResponse(content=HTML)
