from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["god-mode-vault-frontend"])

HTML = """
<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>God Mode Vault</title><style>:root{color-scheme:dark;--panel:#0f172a;--line:#26344f;--text:#eef5ff;--muted:#9fb0d0;--ok:#22c55e}*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:radial-gradient(circle at top,#173766,#050816 55%);color:var(--text)}.page{padding:10px;display:grid;gap:10px}.panel{background:rgba(15,23,42,.94);border:1px solid var(--line);border-radius:22px;padding:13px}h1,h2{margin:.1rem 0}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:8px}.buttons{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}button,input,textarea{font:inherit;border-radius:16px;border:1px solid var(--line);background:#0b1220;color:var(--text);padding:12px}button{background:linear-gradient(135deg,#0284c7,#38bdf8);border:none;color:#02101b;font-weight:1000}button.dark{background:#0b1220;color:var(--text);border:1px solid var(--line)}textarea{width:100%;min-height:180px}.ref{border-left:4px solid var(--ok);padding:9px 10px;background:#081226;border-radius:14px}pre{white-space:pre-wrap;overflow:auto;font-size:12px;max-height:520px;background:#081226;border:1px solid var(--line);border-radius:18px;padding:12px}@media(max-width:760px){.buttons{grid-template-columns:1fr}}</style></head><body><div class="page"><section class="panel"><h1>God Mode Local Vault</h1><p class="muted">Despeja chaves, URLs, tokens, .env e credenciais. O God Mode classifica, ignora placeholders e guarda valores reais no vault local encriptado.</p><div class="buttons"><button onclick="location.href='/app/home'" class="dark">Home</button><button onclick="status()">Status</button><button onclick="refs()">Referências</button></div></section><section class="panel"><h2>Intake bulk</h2><div class="grid"><input id="project" value="GOD_MODE"/><input id="provider" value="auto"/></div><textarea id="bulk"># Cola aqui variáveis .env, URLs e chaves reais quando quiseres guardar no Vault.
# Exemplos placeholder são ignorados:
GITHUB_TOKEN=your_key_here
VERCEL_TOKEN=your_token_here
DATABASE_URL=postgresql://user:pass@example.invalid:5432/db</textarea><button onclick="intake()">Classificar + guardar reais no Vault</button></section><section class="panel"><h2>Planear token necessário</h2><div class="grid"><input id="tokenProvider" value="github"/><input id="purpose" value="repo workflow deploy automation"/></div><button onclick="planToken()">Criar plano de token</button></section><section class="panel"><h2>Referências</h2><div id="items" class="grid"></div></section><section class="panel"><h2>Resultado</h2><pre id="out"></pre></section></div><script>const qs=s=>document.querySelector(s);async function api(p,o){const r=await fetch(p,o);const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={raw:t}};if(!r.ok)throw new Error(t);return j}function esc(s){return String(s??'').replaceAll('<','&lt;')}function show(x){qs('#out').textContent=JSON.stringify(x,null,2);render(x)}function render(x){const refs=x?.vault_references||x?.stored_vault_references?.map(i=>i.vault_reference).filter(Boolean)||[];qs('#items').innerHTML=(Array.isArray(refs)?refs:[]).slice(0,30).map(r=>`<div class="ref"><b>${esc(r.provider)}</b> ${esc(r.secret_kind)}<br>${esc(r.label)}<br><span class="muted">${esc(r.purpose)} | ${esc(r.vault_item_id)}</span></div>`).join('')}async function status(){show(await api('/api/god-mode-vault/status'))}async function refs(){show(await api('/api/god-mode-vault/references?limit=200'))}async function intake(){show(await api('/api/god-mode-vault/intake-text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:qs('#bulk').value,project_hint:qs('#project').value,default_provider:qs('#provider').value,source:'operator_bulk_paste',store_real_values:true})}))}async function planToken(){show(await api('/api/god-mode-vault/plan-needed-token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:qs('#tokenProvider').value,purpose:qs('#purpose').value,project_id:qs('#project').value})}))}status()</script></body></html>
"""


@router.get('/app/god-mode-vault', response_class=HTMLResponse)
async def god_mode_vault_frontend() -> HTMLResponse:
    return HTMLResponse(content=HTML)


@router.get('/app/vault-intake', response_class=HTMLResponse)
async def vault_intake_alias() -> HTMLResponse:
    return HTMLResponse(content=HTML)
