from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["provider-browser-local-launcher-frontend"])

HTML = """
<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Provider Launcher</title><style>:root{color-scheme:dark;--panel:#0f172a;--line:#26344f;--text:#eef5ff;--muted:#9fb0d0}*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:radial-gradient(circle at top,#123256,#050816 55%);color:var(--text)}.page{padding:10px;display:grid;gap:10px}.panel{background:rgba(15,23,42,.94);border:1px solid var(--line);border-radius:22px;padding:13px}h1,h2{margin:.1rem 0}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px}.buttons{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}button,input,textarea,select{font:inherit;border-radius:16px;border:1px solid var(--line);background:#0b1220;color:var(--text);padding:12px}button{background:linear-gradient(135deg,#0284c7,#38bdf8);border:none;color:#02101b;font-weight:1000}button.dark{background:#0b1220;color:var(--text);border:1px solid var(--line)}textarea{width:100%;min-height:220px}pre{white-space:pre-wrap;overflow:auto;font-size:12px;max-height:520px;background:#081226;border:1px solid var(--line);border-radius:18px;padding:12px}@media(max-width:760px){.buttons{grid-template-columns:1fr}}</style></head><body><div class="page"><section class="panel"><h1>Provider Browser Local Launcher</h1><p class="muted">Prepara abertura local no PC + contrato de captura. Não guarda cookies, tokens ou passwords.</p><div class="buttons"><button onclick="location.href='/app/home'" class="dark">Home</button><button onclick="location.href='/app/conversation-source-import-feed'" class="dark">Importar conversa</button><button onclick="dashboard()">Dashboard</button></div></section><section class="panel"><h2>Provider</h2><div class="grid"><select id="provider"><option value="chatgpt">ChatGPT</option><option value="claude">Claude</option><option value="gemini">Gemini</option><option value="perplexity">Perplexity</option><option value="bing_copilot">Copilot</option><option value="local_ollama">Ollama local</option></select><input id="project" value="GOD_MODE"/><input id="tenant" value="owner-andre"/></div><div class="buttons"><button onclick="providerPackage()">Criar launcher + captura + card</button><button class="dark" onclick="launchOnly()">Só launcher</button></div></section><section class="panel"><h2>Importar captura</h2><input id="captureId" placeholder="capture_contract_id"/><textarea id="transcript">Oner: Preciso avançar trabalho real no God Mode e comparar respostas das IAs.
Assistant: Proposta capturada do provider para importar no ledger e Work Map.</textarea><button onclick="importCapture()">Importar captura</button></section><section class="panel"><h2>Resultado</h2><pre id="out"></pre></section></div><script>const qs=s=>document.querySelector(s);async function api(p,o){const r=await fetch(p,o);const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={raw:t}};if(!r.ok)throw new Error(t);return j}function show(x){qs('#out').textContent=JSON.stringify(x,null,2);const cid=x?.capture?.capture_contract?.capture_contract_id||x?.capture_contract?.capture_contract_id;if(cid)qs('#captureId').value=cid}async function providerPackage(){show(await api('/api/provider-browser-local-launcher/package-provider',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider_id:qs('#provider').value,project_hint:qs('#project').value,tenant_id:qs('#tenant').value})}))}async function launchOnly(){show(await api('/api/provider-browser-local-launcher/create-launch-contract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider_id:qs('#provider').value,project_hint:qs('#project').value,tenant_id:qs('#tenant').value})}))}async function importCapture(){show(await api('/api/provider-browser-local-launcher/import-capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({capture_contract_id:qs('#captureId').value,transcript_text:qs('#transcript').value,tenant_id:qs('#tenant').value})}))}async function dashboard(){show(await api('/api/provider-browser-local-launcher/dashboard'))}dashboard()</script></body></html>
"""


@router.get('/app/provider-browser-local-launcher', response_class=HTMLResponse)
async def provider_browser_local_launcher_frontend() -> HTMLResponse:
    return HTMLResponse(content=HTML)


@router.get('/app/provider-launcher', response_class=HTMLResponse)
async def provider_launcher_alias() -> HTMLResponse:
    return HTMLResponse(content=HTML)
